package asacIntents;

/**
 * Created by michele on 19/07/16.
 */
public class AsacIntents
{
    public static final String RADIO_INTENSITY_CHANGED_RSSI = "RADIO_INTENSITY_CHANGED_RSSI";
    public static final String RADIO_INTENSITY_CHANGED_STRENGTH = "RADIO_INTENSITY_CHANGED_STRENGTH";
    public static final String RADIO_INTENSITY_CHANGED_WORK_MODE = "RADIO_INTENSITY_CHANGED_WORK_MODE";
    public static final String RADIO_INTENSITY_CHANGED_STRENGTH_INT = "RADIO_INTENSITY_CHANGED_STRENGTH_INT";
    public static final String RADIO_INTENSITY_CHANGED_WORK_MODE_INT = "RADIO_INTENSITY_CHANGED_WORK_MODE_INT";

    public static final String RX_FILE_STATS_CHANGED_NUM_OF_BYTES_RX = "RX_FILE_STATS_CHANGED_NUM_OF_BYTES_RX";
    public static final String RX_FILE_STATS_CHANGED_HOST_FILE_SIZE = "RX_FILE_STATS_CHANGED_HOST_FILE_SIZE";

    public static final String TX_FILE_STATS_CHANGED_NUM_OF_BYTES_TX = "TX_FILE_STATS_CHANGED_NUM_OF_BYTES_TX";
    public static final String TX_FILE_STATS_CHANGED_LOCAL_FILE_SIZE = "TX_FILE_STATS_CHANGED_LOCAL_FILE_SIZE";

}
